"""add_threat_patterns_and_reports

Revision ID: 79d81b426792
Revises: b46613359996
Create Date: 2026-04-03 04:58:02.254867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d81b426792'
down_revision: Union[str, Sequence[str], None] = 'b46613359996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(length=20), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_patterns_id'), 'threat_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_threat_patterns_pattern_type'), 'threat_patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_threat_patterns_value'), 'threat_patterns', ['value'], unique=True)
    op.add_column('scam_keywords', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scam_keywords', 'weight')
    op.drop_index(op.f('ix_threat_patterns_value'), table_name='threat_patterns')
    op.drop_index(op.f('ix_threat_patterns_pattern_type'), table_name='threat_patterns')
    op.drop_index(op.f('ix_threat_patterns_id'), table_name='threat_patterns')
    op.drop_table('threat_patterns')
    # ### end Alembic commands ###
