"""initial_forensics_schema

Revision ID: b46613359996
Revises: 
Create Date: 2026-04-03 03:06:48.783037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b46613359996'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'])
    op.add_column('scam_keywords', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('scam_keywords', 'keyword',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('keyword'), table_name='scam_keywords')
    op.create_index(op.f('ix_scam_keywords_id'), 'scam_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_scam_keywords_keyword'), 'scam_keywords', ['keyword'], unique=True)
    op.drop_column('scam_keywords', 'risk_level')
    op.create_foreign_key(None, 'scam_reports', 'users', ['user_id'], ['id'])
    op.alter_column('scan_records', 'scan_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('scan_records', 'reasoning',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('scan_records', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('ix_scan_records_id'), 'scan_records', ['id'], unique=False)
    op.create_index(op.f('ix_scan_records_user_id'), 'scan_records', ['user_id'], unique=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('student', 'admin'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'student'"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('student', 'admin'),
               existing_nullable=True,
               existing_server_default=sa.text("'student'"))
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_scan_records_user_id'), table_name='scan_records')
    op.drop_index(op.f('ix_scan_records_id'), table_name='scan_records')
    op.alter_column('scan_records', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('scan_records', 'reasoning',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('scan_records', 'scan_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'scam_reports', type_='foreignkey')
    op.add_column('scam_keywords', sa.Column('risk_level', mysql.VARCHAR(length=20), server_default=sa.text("'high'"), nullable=True))
    op.drop_index(op.f('ix_scam_keywords_keyword'), table_name='scam_keywords')
    op.drop_index(op.f('ix_scam_keywords_id'), table_name='scam_keywords')
    op.create_index(op.f('keyword'), 'scam_keywords', ['keyword'], unique=True)
    op.alter_column('scam_keywords', 'keyword',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('scam_keywords', 'created_at')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    # ### end Alembic commands ###
